POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "anh1",
  "email": "phamtienanhit@gmail.com",
  "password": "123456"
}

###

POST  http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "anh1",
  "password": "123456"
}
###
GET   http://localhost:6000/api/user
Content-Type: application/json

###
DELETE  http://localhost:6000/api/user/62bd341e83837ef16ab55167
Content-Type: application/json

###
POST http://localhost:6000/api/product/
Content-Type: application/json

{
  "title": "Razer Kraken Gaming Headset: Lightweight Aluminum Frame, Retractable Noise Isolating Microphone, For PC, PS4, PS5, Switch, Xbox One, Xbox Series X & S, Mobile, 3.5 mm Audio Jack Green",
  "category": "Headsets",
  "price": 39.99,
  "rating": 4,
  "discout": 50,
   "image": "https://m.media-amazon.com/images/I/71BKQhFzDmL._AC_UY327_FMwebp_QL65_.jpg"
}
