POST http://localhost:7000/api/auth/register
Content-Type: application/json

{
  "username": "anh",
  "email": "phamtienanhit@gmail.com",
  "password": "2222222"
}

###

POST http://localhost:7000/api/auth/login
Content-Type: application/json

{
  "email": "tienanhnvpl@gmail.com",
  "password": "222222"
}

###

POST http://localhost:7000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmI4MTk2Y2ZkN2ViZjA0NWMxNTQyMDkiLCJpYXQiOjE2NTYyNDUzMDd9.CKK7YhHHpuWGi_qK_lBUbbkdAcmzplzMMLusrquA-vM

{
  "title": "React",
  "description": "React",
  "url": "react.com",
  "status": "TO LEARN"
}

###

GET http://localhost:7000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmI4MTk2Y2ZkN2ViZjA0NWMxNTQyMDkiLCJpYXQiOjE2NTYyNDIzNTh9.LvaBLO5LU013U2V_bW-RToC4S7V8jFt1YqLOZMKTzZc
###

PUT http://localhost:7000/api/posts/62b8196cfd7ebf045c154209
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmI4MTk2Y2ZkN2ViZjA0NWMxNTQyMDkiLCJpYXQiOjE2NTYyNDIzNTh9.LvaBLO5LU013U2V_bW-RToC4S7V8jFt1YqLOZMKTzZc

{
  "title": "Vue",
  "description": "VUEEEEE",
  "url": "https://vuejs.org",
  "status": "LEARNING"
}

###

DELETE http://localhost:7000/api/posts/62b8196cfd7ebf045c154209
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmI4MTk2Y2ZkN2ViZjA0NWMxNTQyMDkiLCJpYXQiOjE2NTYyNDIzNTh9.LvaBLO5LU013U2V_bW-RToC4S7V8jFt1YqLOZMKTzZc

