POST http://localhost:7000/api/auth/register
Content-Type: application/json

{
  "username": "jim",
  "password": "jim"
}

###

POST http://localhost:7000/api/auth/login
Content-Type: application/json

{
  "username": "jim",
  "password": "jim"
}

